// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimFit360.Data;

#nullable disable

namespace SimFit360.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240305090322_barcode")]
    partial class barcode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SimFit360.Classes.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Kcal")
                        .HasColumnType("int");

                    b.Property<int>("MaschineId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaschineId");

                    b.HasIndex("UserId");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kcal = 200,
                            MaschineId = 1,
                            Time = new TimeSpan(0, 0, 35, 0, 0),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2024, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kcal = 300,
                            MaschineId = 2,
                            Time = new TimeSpan(0, 0, 40, 0, 0),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2024, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kcal = 400,
                            MaschineId = 3,
                            Time = new TimeSpan(0, 0, 50, 0, 0),
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2024, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kcal = 500,
                            MaschineId = 4,
                            Time = new TimeSpan(0, 1, 5, 0, 0),
                            UserId = 4
                        });
                });

            modelBuilder.Entity("SimFit360.Classes.Badge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Badges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Beginner"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Intermediate"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Advanced"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Expert"
                        });
                });

            modelBuilder.Entity("SimFit360.Classes.Maschine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Maschines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Treadmill"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bike"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rowing machine"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cross trainer"
                        });
                });

            modelBuilder.Entity("SimFit360.Classes.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Barcode")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Pincode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = 1010101,
                            Email = "jeroen@gmail.com",
                            Name = "Jeroen",
                            Pincode = 0
                        },
                        new
                        {
                            Id = 2,
                            Barcode = 12121212,
                            Email = "boyan@gmail.com",
                            Name = "Boyan",
                            Pincode = 1111
                        },
                        new
                        {
                            Id = 3,
                            Barcode = 23232323,
                            Email = "caltan@gmail.com",
                            Name = "Caltan",
                            Pincode = 2222
                        },
                        new
                        {
                            Id = 4,
                            Barcode = 34343434,
                            Email = "junbo@gmail.com",
                            Name = "Junbo",
                            Pincode = 3333
                        });
                });

            modelBuilder.Entity("SimFit360.Classes.UserBadges", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BadgeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserBadges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BadgeId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            BadgeId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            BadgeId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            BadgeId = 4,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("SimFit360.Classes.Activity", b =>
                {
                    b.HasOne("SimFit360.Classes.Maschine", "Maschine")
                        .WithMany()
                        .HasForeignKey("MaschineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimFit360.Classes.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Maschine");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
